ARIMA:
  p: 1           # Autoregressive order
  d: 0           # Differencing order
  q: 1           # Moving average order

ElasticNet:
  alpha: 1.0     # L1 regularization parameter
  l1_ratio: 0.5  # Mix of L1 and L2 regularization