COLUMNS:
  Common Type of Seed: object
  Daily Hay Dry matter (kg): int64
  Daily Hay Intake Fresh (kg): int64
  dry matter: float64
  net energy for lactation of hay: float64
  


TARGET_COLUMN:
  Body Weight (kg): int64
  