artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://dagshub.com/Omdena/NorthCarolina_CameroonChapter_AngusIssues/raw/74614110d76b9179e1e6f729d9d57b607b46b2f6/dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
